apiVersion: v1
kind: Service
metadata:
  name: eurekaservice
  namespace: dev
spec:
  ports:
    - name: http
      port: 8761
    - name: https
      port: 443
  type: LoadBalancer    
  selector:
    app: eurekaservice